/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMentorRouteImport } from './routes/api/mentor'
import { Route as ApiImoveisRouteImport } from './routes/api/imoveis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel/index'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiPublicProtocoloRouteImport } from './routes/api/public/protocolo'
import { Route as AuthenticatedProjetoIdRouteImport } from './routes/_authenticated/projeto.$id'
import { Route as AuthenticatedPainelProjetosRouteImport } from './routes/_authenticated/painel/projetos'
import { Route as AuthenticatedPainelPresenteRouteImport } from './routes/_authenticated/painel/presente'
import { Route as AuthenticatedPainelPortfolioRouteImport } from './routes/_authenticated/painel/portfolio'
import { Route as AuthenticatedPainelMentorRouteImport } from './routes/_authenticated/painel/mentor'
import { Route as AuthenticatedPainelCriarRouteImport } from './routes/_authenticated/painel/criar'
import { Route as AuthenticatedPainelCreditosRouteImport } from './routes/_authenticated/painel/creditos'
import { Route as AuthenticatedPainelContaRouteImport } from './routes/_authenticated/painel/conta'
import { Route as AuthenticatedProjetoRouteImport } from './routes/_authenticated/projeto.'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorRoute = ApiMentorRouteImport.update({
  id: '/api/mentor',
  path: '/api/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImoveisRoute = ApiImoveisRouteImport.update({
  id: '/api/imoveis',
  path: '/api/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/painel/',
    path: '/painel/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProtocoloRoute = ApiPublicProtocoloRouteImport.update({
  id: '/api/public/protocolo',
  path: '/api/public/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetoIdRoute = AuthenticatedProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelProjetosRoute =
  AuthenticatedPainelProjetosRouteImport.update({
    id: '/painel/projetos',
    path: '/painel/projetos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelPresenteRoute =
  AuthenticatedPainelPresenteRouteImport.update({
    id: '/painel/presente',
    path: '/painel/presente',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelPortfolioRoute =
  AuthenticatedPainelPortfolioRouteImport.update({
    id: '/painel/portfolio',
    path: '/painel/portfolio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelMentorRoute =
  AuthenticatedPainelMentorRouteImport.update({
    id: '/painel/mentor',
    path: '/painel/mentor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelCriarRoute =
  AuthenticatedPainelCriarRouteImport.update({
    id: '/painel/criar',
    path: '/painel/criar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelCreditosRoute =
  AuthenticatedPainelCreditosRouteImport.update({
    id: '/painel/creditos',
    path: '/painel/creditos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPainelContaRoute =
  AuthenticatedPainelContaRouteImport.update({
    id: '/painel/conta',
    path: '/painel/conta',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjetoRoute = AuthenticatedProjetoRouteImport.update({
  id: '/projeto/',
  path: '/projeto/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/imoveis': typeof ApiImoveisRoute
  '/api/mentor': typeof ApiMentorRoute
  '/projeto/': typeof AuthenticatedProjetoRoute
  '/painel/conta': typeof AuthenticatedPainelContaRoute
  '/painel/creditos': typeof AuthenticatedPainelCreditosRoute
  '/painel/criar': typeof AuthenticatedPainelCriarRoute
  '/painel/mentor': typeof AuthenticatedPainelMentorRoute
  '/painel/portfolio': typeof AuthenticatedPainelPortfolioRoute
  '/painel/presente': typeof AuthenticatedPainelPresenteRoute
  '/painel/projetos': typeof AuthenticatedPainelProjetosRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/public/protocolo': typeof ApiPublicProtocoloRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/imoveis': typeof ApiImoveisRoute
  '/api/mentor': typeof ApiMentorRoute
  '/projeto': typeof AuthenticatedProjetoRoute
  '/painel/conta': typeof AuthenticatedPainelContaRoute
  '/painel/creditos': typeof AuthenticatedPainelCreditosRoute
  '/painel/criar': typeof AuthenticatedPainelCriarRoute
  '/painel/mentor': typeof AuthenticatedPainelMentorRoute
  '/painel/portfolio': typeof AuthenticatedPainelPortfolioRoute
  '/painel/presente': typeof AuthenticatedPainelPresenteRoute
  '/painel/projetos': typeof AuthenticatedPainelProjetosRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/public/protocolo': typeof ApiPublicProtocoloRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/imoveis': typeof ApiImoveisRoute
  '/api/mentor': typeof ApiMentorRoute
  '/_authenticated/projeto/': typeof AuthenticatedProjetoRoute
  '/_authenticated/painel/conta': typeof AuthenticatedPainelContaRoute
  '/_authenticated/painel/creditos': typeof AuthenticatedPainelCreditosRoute
  '/_authenticated/painel/criar': typeof AuthenticatedPainelCriarRoute
  '/_authenticated/painel/mentor': typeof AuthenticatedPainelMentorRoute
  '/_authenticated/painel/portfolio': typeof AuthenticatedPainelPortfolioRoute
  '/_authenticated/painel/presente': typeof AuthenticatedPainelPresenteRoute
  '/_authenticated/painel/projetos': typeof AuthenticatedPainelProjetosRoute
  '/_authenticated/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/public/protocolo': typeof ApiPublicProtocoloRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/perfil'
    | '/api/imoveis'
    | '/api/mentor'
    | '/projeto/'
    | '/painel/conta'
    | '/painel/creditos'
    | '/painel/criar'
    | '/painel/mentor'
    | '/painel/portfolio'
    | '/painel/presente'
    | '/painel/projetos'
    | '/projeto/$id'
    | '/api/public/protocolo'
    | '/api/public/webhook'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/perfil'
    | '/api/imoveis'
    | '/api/mentor'
    | '/projeto'
    | '/painel/conta'
    | '/painel/creditos'
    | '/painel/criar'
    | '/painel/mentor'
    | '/painel/portfolio'
    | '/painel/presente'
    | '/painel/projetos'
    | '/projeto/$id'
    | '/api/public/protocolo'
    | '/api/public/webhook'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/perfil'
    | '/api/imoveis'
    | '/api/mentor'
    | '/_authenticated/projeto/'
    | '/_authenticated/painel/conta'
    | '/_authenticated/painel/creditos'
    | '/_authenticated/painel/criar'
    | '/_authenticated/painel/mentor'
    | '/_authenticated/painel/portfolio'
    | '/_authenticated/painel/presente'
    | '/_authenticated/painel/projetos'
    | '/_authenticated/projeto/$id'
    | '/api/public/protocolo'
    | '/api/public/webhook'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiImoveisRoute: typeof ApiImoveisRoute
  ApiMentorRoute: typeof ApiMentorRoute
  ApiPublicProtocoloRoute: typeof ApiPublicProtocoloRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor': {
      id: '/api/mentor'
      path: '/api/mentor'
      fullPath: '/api/mentor'
      preLoaderRoute: typeof ApiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imoveis': {
      id: '/api/imoveis'
      path: '/api/imoveis'
      fullPath: '/api/imoveis'
      preLoaderRoute: typeof ApiImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/protocolo': {
      id: '/api/public/protocolo'
      path: '/api/public/protocolo'
      fullPath: '/api/public/protocolo'
      preLoaderRoute: typeof ApiPublicProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projeto/$id': {
      id: '/_authenticated/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof AuthenticatedProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/projetos': {
      id: '/_authenticated/painel/projetos'
      path: '/painel/projetos'
      fullPath: '/painel/projetos'
      preLoaderRoute: typeof AuthenticatedPainelProjetosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/presente': {
      id: '/_authenticated/painel/presente'
      path: '/painel/presente'
      fullPath: '/painel/presente'
      preLoaderRoute: typeof AuthenticatedPainelPresenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/portfolio': {
      id: '/_authenticated/painel/portfolio'
      path: '/painel/portfolio'
      fullPath: '/painel/portfolio'
      preLoaderRoute: typeof AuthenticatedPainelPortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/mentor': {
      id: '/_authenticated/painel/mentor'
      path: '/painel/mentor'
      fullPath: '/painel/mentor'
      preLoaderRoute: typeof AuthenticatedPainelMentorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/criar': {
      id: '/_authenticated/painel/criar'
      path: '/painel/criar'
      fullPath: '/painel/criar'
      preLoaderRoute: typeof AuthenticatedPainelCriarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/creditos': {
      id: '/_authenticated/painel/creditos'
      path: '/painel/creditos'
      fullPath: '/painel/creditos'
      preLoaderRoute: typeof AuthenticatedPainelCreditosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel/conta': {
      id: '/_authenticated/painel/conta'
      path: '/painel/conta'
      fullPath: '/painel/conta'
      preLoaderRoute: typeof AuthenticatedPainelContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projeto/': {
      id: '/_authenticated/projeto/'
      path: '/projeto'
      fullPath: '/projeto/'
      preLoaderRoute: typeof AuthenticatedProjetoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProjetoRoute: typeof AuthenticatedProjetoRoute
  AuthenticatedPainelContaRoute: typeof AuthenticatedPainelContaRoute
  AuthenticatedPainelCreditosRoute: typeof AuthenticatedPainelCreditosRoute
  AuthenticatedPainelCriarRoute: typeof AuthenticatedPainelCriarRoute
  AuthenticatedPainelMentorRoute: typeof AuthenticatedPainelMentorRoute
  AuthenticatedPainelPortfolioRoute: typeof AuthenticatedPainelPortfolioRoute
  AuthenticatedPainelPresenteRoute: typeof AuthenticatedPainelPresenteRoute
  AuthenticatedPainelProjetosRoute: typeof AuthenticatedPainelProjetosRoute
  AuthenticatedProjetoIdRoute: typeof AuthenticatedProjetoIdRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProjetoRoute: AuthenticatedProjetoRoute,
  AuthenticatedPainelContaRoute: AuthenticatedPainelContaRoute,
  AuthenticatedPainelCreditosRoute: AuthenticatedPainelCreditosRoute,
  AuthenticatedPainelCriarRoute: AuthenticatedPainelCriarRoute,
  AuthenticatedPainelMentorRoute: AuthenticatedPainelMentorRoute,
  AuthenticatedPainelPortfolioRoute: AuthenticatedPainelPortfolioRoute,
  AuthenticatedPainelPresenteRoute: AuthenticatedPainelPresenteRoute,
  AuthenticatedPainelProjetosRoute: AuthenticatedPainelProjetosRoute,
  AuthenticatedProjetoIdRoute: AuthenticatedProjetoIdRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiImoveisRoute: ApiImoveisRoute,
  ApiMentorRoute: ApiMentorRoute,
  ApiPublicProtocoloRoute: ApiPublicProtocoloRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
