/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMentorRouteImport } from './routes/api/mentor'
import { Route as ApiImoveisRouteImport } from './routes/api/imoveis'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as ApiPublicWebhookRouteImport } from './routes/api/public/webhook'
import { Route as ApiPublicProtocoloRouteImport } from './routes/api/public/protocolo'
import { Route as AuthenticatedProjetoIdRouteImport } from './routes/_authenticated/projeto.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMentorRoute = ApiMentorRouteImport.update({
  id: '/api/mentor',
  path: '/api/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImoveisRoute = ApiImoveisRouteImport.update({
  id: '/api/imoveis',
  path: '/api/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhookRoute = ApiPublicWebhookRouteImport.update({
  id: '/api/public/webhook',
  path: '/api/public/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProtocoloRoute = ApiPublicProtocoloRouteImport.update({
  id: '/api/public/protocolo',
  path: '/api/public/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjetoIdRoute = AuthenticatedProjetoIdRouteImport.update({
  id: '/projeto/$id',
  path: '/projeto/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/imoveis': typeof ApiImoveisRoute
  '/api/mentor': typeof ApiMentorRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/public/protocolo': typeof ApiPublicProtocoloRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/api/imoveis': typeof ApiImoveisRoute
  '/api/mentor': typeof ApiMentorRoute
  '/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/public/protocolo': typeof ApiPublicProtocoloRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/api/imoveis': typeof ApiImoveisRoute
  '/api/mentor': typeof ApiMentorRoute
  '/_authenticated/projeto/$id': typeof AuthenticatedProjetoIdRoute
  '/api/public/protocolo': typeof ApiPublicProtocoloRoute
  '/api/public/webhook': typeof ApiPublicWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/painel'
    | '/perfil'
    | '/api/imoveis'
    | '/api/mentor'
    | '/projeto/$id'
    | '/api/public/protocolo'
    | '/api/public/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/painel'
    | '/perfil'
    | '/api/imoveis'
    | '/api/mentor'
    | '/projeto/$id'
    | '/api/public/protocolo'
    | '/api/public/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/obrigado'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/painel'
    | '/_authenticated/perfil'
    | '/api/imoveis'
    | '/api/mentor'
    | '/_authenticated/projeto/$id'
    | '/api/public/protocolo'
    | '/api/public/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  ApiImoveisRoute: typeof ApiImoveisRoute
  ApiMentorRoute: typeof ApiMentorRoute
  ApiPublicProtocoloRoute: typeof ApiPublicProtocoloRoute
  ApiPublicWebhookRoute: typeof ApiPublicWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mentor': {
      id: '/api/mentor'
      path: '/api/mentor'
      fullPath: '/api/mentor'
      preLoaderRoute: typeof ApiMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/imoveis': {
      id: '/api/imoveis'
      path: '/api/imoveis'
      fullPath: '/api/imoveis'
      preLoaderRoute: typeof ApiImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhook': {
      id: '/api/public/webhook'
      path: '/api/public/webhook'
      fullPath: '/api/public/webhook'
      preLoaderRoute: typeof ApiPublicWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/protocolo': {
      id: '/api/public/protocolo'
      path: '/api/public/protocolo'
      fullPath: '/api/public/protocolo'
      preLoaderRoute: typeof ApiPublicProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projeto/$id': {
      id: '/_authenticated/projeto/$id'
      path: '/projeto/$id'
      fullPath: '/projeto/$id'
      preLoaderRoute: typeof AuthenticatedProjetoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedProjetoIdRoute: typeof AuthenticatedProjetoIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedProjetoIdRoute: AuthenticatedProjetoIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  ApiImoveisRoute: ApiImoveisRoute,
  ApiMentorRoute: ApiMentorRoute,
  ApiPublicProtocoloRoute: ApiPublicProtocoloRoute,
  ApiPublicWebhookRoute: ApiPublicWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
